function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function domainOf(request){const d=(new URL(request.url).searchParams.get("domain")||"").trim().toLowerCase();return d&&d.includes(".")&&!/[\/@ :]/.test(d)?d:null}
async function fj(url,ms=6500,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{"accept":"application/json,text/plain,*/*","user-agent":"DomainBackstory/16.0",...headers},signal:c.signal});if(!r.ok){const e=new Error("Provider HTTP "+r.status);e.status=r.status;throw e}return await r.json()}finally{clearTimeout(t)}}
async function cached(k,ttl,fn,ctx){const cache=caches.default,key=new Request(k),hit=await cache.match(key);if(hit){const x=await hit.json();x.cached=true;return x}const x=await fn();ctx.waitUntil(cache.put(key,new Response(JSON.stringify(x),{headers:{"content-type":"application/json","cache-control":`public,s-maxage=${ttl}`}})));return x}
async function bootstrap(domain){const tld=domain.split(".").pop(),b=await fj("https://data.iana.org/rdap/dns.json",5000);for(const s of b.services||[]){if((s[0]||[]).map(x=>String(x).toLowerCase()).includes(tld)){let u=(s[1]||[])[0];if(u){if(!u.endsWith("/"))u+="/";return u+"domain/"+encodeURIComponent(domain)}}}return null}
function parseRdap(x,domain,source){const ev={};for(const e of x.events||[])if(e.eventAction&&e.eventDate&&!ev[e.eventAction])ev[e.eventAction]=e.eventDate;let registrar=null,iana=null;for(const en of x.entities||[]){if(!(en.roles||[]).includes("registrar"))continue;for(const i of en.vcardArray?.[1]||[])if(i[0]==="fn"&&!registrar)registrar=i[3];for(const id of en.publicIds||[])if((id.type||"").toLowerCase().includes("iana"))iana=id.identifier;break}return{domain:(x.ldhName||domain).toLowerCase(),created:ev.registration||null,changed:ev["last changed"]||ev.changed||null,transfer:ev.transfer||null,expires:ev.expiration||null,registrar,registrar_iana_id:iana,nameservers:(x.nameservers||[]).map(n=>(n.ldhName||n.unicodeName||"").toLowerCase()).filter(Boolean),status:x.status||[],source}}
async function rdap(domain){const errs=[];try{const u=await bootstrap(domain);if(u)return parseRdap(await fj(u,6500),domain,"registry")}catch(e){errs.push("registry: "+e.message)}try{return parseRdap(await fj("https://rdap.org/domain/"+encodeURIComponent(domain),6500),domain,"rdap.org")}catch(e){errs.push("rdap.org: "+e.message)}throw new Error(errs.join(" | "))}
function strip(s){return String(s||"").replace(/\.$/,"")}
async function doh(domain,type){const x=await fj(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(domain)}&type=${type}`,5500,{"accept":"application/dns-json"});return(x.Answer||[]).map(a=>{let d=String(a.data||"");if(type==="MX"){const m=d.match(/^(\d+)\s+(.+)$/);return m?`${m[1]} ${strip(m[2])}`:strip(d)}if(type==="SOA")return d.split(" ").slice(0,2).map(strip).join(" ");return strip(d.replace(/^"|"$/g,""))}).filter(Boolean)}
async function dns(domain){const types=["A","AAAA","MX","NS","CNAME","SOA"],out={},r=await Promise.allSettled(types.map(t=>doh(domain,t)));types.forEach((t,i)=>out[t]=r[i].status==="fulfilled"?r[i].value:[]);return out}
async function maildns(domain){const [a,b]=await Promise.allSettled([doh(domain,"TXT"),doh("_dmarc."+domain,"TXT")]);const x=a.status==="fulfilled"?a.value:[],y=b.status==="fulfilled"?b.value:[];return{spf:x.find(v=>/^v=spf1\b/i.test(v))||null,dmarc:y.find(v=>/^v=dmarc1\b/i.test(v))||null}}
function snap(x){const c=x?.archived_snapshots?.closest;if(!c)return{available:false,timestamp:null,url:null,status:null};const ts=c.timestamp||"",iso=ts.length>=8?`${ts.slice(0,4)}-${ts.slice(4,6)}-${ts.slice(6,8)}T00:00:00Z`:ts;return{available:!!c.available,timestamp:iso,url:c.url||null,status:c.status||null}}
async function wayback(domain){const base="https://archive.org/wayback/available?url="+encodeURIComponent(domain),r=await Promise.allSettled([fj(base+"&timestamp=19900101",5500),fj(base,5500)]);if(r[0].status==="rejected"&&r[1].status==="rejected")throw new Error("Wayback unavailable");return{oldest:r[0].status==="fulfilled"?snap(r[0].value):{available:false},latest:r[1].status==="fulfilled"?snap(r[1].value):{available:false}}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(!u.pathname.startsWith("/api/"))return env.ASSETS.fetch(request);const d=domainOf(request);if(!d)return json({error:"Invalid domain"},400);try{if(u.pathname==="/api/rdap")return json(await cached(`https://cache.db/v16/rdap/${d}`,86400,()=>rdap(d),ctx));if(u.pathname==="/api/dns")return json(await cached(`https://cache.db/v16/dns/${d}`,3600,()=>dns(d),ctx));if(u.pathname==="/api/maildns")return json(await cached(`https://cache.db/v16/mail/${d}`,3600,()=>maildns(d),ctx));if(u.pathname==="/api/wayback")return json(await cached(`https://cache.db/v16/web/${d}`,43200,()=>wayback(d),ctx));return json({error:"Not found"},404)}catch(e){return json({error:e.name==="AbortError"?"Provider timed out":e.message},502)}}}